### ISSUE TITLE
Install fails with Python 3.9

### ISSUE THREAD

**Issue by gschivley** [NREL/OpenOA#114]
The installation instructions say to do

```
conda create --name openoa-env python=3
```

which now installs python 3.9. I tried to install one final time (previous laptop died) to finish my review, and it looks like there are issues (maybe some missing wheels, maybe just on Mac?). I had to specify python 3.8 to install.

Part of review (openjournals/joss-reviews#2171)

**Comment by brynpickering** [comment]
I also came across this issue on OSX, similarly solved by forcing `python=3.8`.

Note: this comment comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2171)

**Comment by jordanperr** [comment]
This seems to be an issue with many packages right now. Please proceed reviewing OpenOA assuming the Python 3.8 dependency - and we will work to figure out the long term solution for Python 3.9.

**Comment by jordanperr** [comment]
The main reason for install failure is that Shapely does not have binary wheels for Mac + Python 3.9. This is an issue specific to Macs running Python 3.9. There is an open ticket for this in the Shapely issue tracker. People in this thread suggest using brew to first install geos (which is the critical missing dependency for Shapely) before trying to install Shapely. This workaround will likely work for OpenOA, but I am have not tested it.

For now:
- Readme will be updated to recommend Python 3.8.
- I will leave this issue open until OpenOA supports Python 3.9 on all platforms.

Thanks again for reporting this.

https://github.com/Toblerity/Shapely/issues/1040
