### ISSUE TITLE
Example notebooks package requirements

### ISSUE THREAD

**Issue by brynpickering** [NREL/OpenOA#115]
It would be nice to jump into the example notebooks without having to deal with `ModuleNotFound` errors once working in them. Would it be possible to have a requirements file in the examples directory, containing all the additional packages required in the example notebooks? It could also include jupyter itself (or, at least, ipykernel). 

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2171)

**Comment by brynpickering** [comment]
I see that the main missing requirement from the standard setup is matplotlib. matplotlib is in the top-level `requirements.txt`, but this then would install development-based packages that users looking at the examples probably don't care about. 

Perhaps it isn't worth it for just jupyter and matplotlib in the examples directory requirements; happy for you to close this if you also think it isn't worth it.

**Comment by jordanperr** [comment]
I like the idea of a separate requirements file for the example notebooks. We can add Jupyter there, as well.

**Comment by jordanperr** [comment]
This has been fixed in #117
