### ISSUE TITLE
JOSS paper cleanup, content, and structure

### ISSUE THREAD

**Issue by brynpickering** [NREL/OpenOA#119]
The JOSS paper looks to cover everything I'd expect, but would benefit from a few cleanups:

- [x] Define abbreviations at least once (e.g. AEP, SCADA), or just avoid using them altogether. In the case of AEP, it is not a well known abbreviation (unlike e.g. PV for solar photovoltaic panels), so I'd have preference for it not being used at all.

- [x] Links to (undated) websites would look better as just hyperlinked text. I.e. don't bother including it in the list of references.

- [x] Reference to literature published by NREL should ideally use the 'shortauthor' format, so that the in-text citation reads `NREL` rather than `Laboratory`. Not sure how to make this happen in Markdown, but would be worth investigating.

- [x] Link to ReadtheDocs hasn't rendered. Instead, the generated PDF just shows `[^rtdwebsite]`

- [x] Some misplaced periods in `Version 2 of OpenOA implements three high level analysis methods. (1) Long term corrected AEP. (2) Electrical losses, and (3) Turbine level losses.`. Possibly should be `Version 2 of OpenOA implements three high level analysis methods: (1) Long term corrected AEP, (2) Electrical losses, and (3) Turbine level losses.`

### structure
- [x] The initial paragraph would be better placed in the summary (and the summary placed before the statement of need). If you want to retain the first paragraph, then you should place more importance on describing its high-level functionality than on the credentials of the github repository.

### content
- [x] The paper seems to be missing any reference to other similar and commonly-used packages in the research area. This is a listed criterion in the [JOSS submission guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper)
- [x] You produce a number of informative figures in your example notebooks. Placing one or two of these in your paper might further aid readers in understanding the purpose of the software. 

Note: this issue comes to you as part of my wider [JOSS review](https://github.com/openjournals/joss-reviews/issues/2171)

Edit: added in structure and content comments into this issue so everything is kept in one place.

**Comment by jordanperr** [comment]
Thank you for the suggestions, @brynpickering. The latest version in the joss-review branch addresses many of the changes. Specifically:

- I have integrated all of the smaller style and grammar changes that were suggested.
- Re-arranged the summary section to incorporate more language about uses of the software earlier on. Combined the abstract with the summary section as suggested.
- Ensure all abbreviations are defined
- Added a figure with example graphs from the documentation.
- Additionally: We know of no other open source software package that is built to compute 20-year long term corrected AEP metric from operational data. Practitioners in the field typically write their own code to compute this metric using foundational libraries such as numpy or scikit-learn. There are some companies that offer AEP as part of a commercial software offering, but these products are not open source. I have added a couple sentences around lines 55-58 to clarify this point.

Thank You. Please let me know if you have any other suggestions.

**Comment by brynpickering** [comment]
Looks good to me!
