### ISSUE TITLE
Convert all toolkit functions to operate on Pandas.Series and Numpy.Array

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#12]
Some functions in toolkits take a dataframe as their first argument, and then strings that represent column names of this dataframe. We'd like to migrate these functions to operate on Series and Array, avoiding the need to pass the entire dataframe and string column names. This will allow for more flexibility in their use. The following functions shall be converted:

- [x] met_toolkit.py ( merge in PR #49 )

- compute_air_density
- air_density_adjusted_wind_speed
- compute_turbulence_intensity
- compute_shear
- compute_veer

- [x] imputing.py

- correlation_matrix_by_id_column
- impute_data
- impute_all_assets_by_correlation

- [x] unit_conversion.py

- convert_feet_to_meter (documentation)
- convert_power_to_energy (documentation)

**Comment by jordanperr** [comment]
Let's apply these changes where its easy (i.e. met data). Unit conversion is already changed. For imputing, leave it alone for now and revisit when we parallelize the scada dataframe.

**Comment by nateagarwal** [comment]
@jordanperr I recently submitted a PR that converts all of the met functions (except for the shear calculation) to operate on both pandas.series and NumPy.array types.

**Comment by jordanperr** [comment]
Closing this issue as it is out of date.
