### ISSUE TITLE
sklearn.metrics.scorer

### ISSUE THREAD

**Issue by kubilay** [NREL/OpenOA#122]
Hello,

While trying to install OpenOA to a computer on a plain python installation with no anaconda, I have came up with a problem on python noteboooks which leads to machine_learning_setup.py: ModuleNotFoundError: No module named 'sklearn.metrics.scorer' . It is easily resolved after removing, and updating the line 
`from sklearn.metrics.scorer import make_scorer`
to
`from sklearn.metrics import make_scorer`

Kubilay.

**Comment by nbodini** [comment]
Hello Kubilay,
We have addressed this in PR #102 , which should be merged soon!
Thank you!
