### ISSUE TITLE
plant_analysis.MonteCarloAEP.run fails when wind direction is included

### ISSUE THREAD

**Issue by ejsimley** [NREL/OpenOA#123]
When running the MonteCarloAEP analysis with wind direction included as a regression input, the `plant_analysis.MonteCarloAEP.run` method fails at `apply_IAV`. The error can be encountered when running the example 2b notebook in either the linear regression (section 1.2) or machine learning (section 1.3) sections.

Note that including wind speed and temperature as regression inputs does not cause the AEP analysis to fail, so it seems to be related to wind direction specifically.

Because PR#102 removes IAV, the error goes away when testing the pull request. We should verify that after merging PR#102, including wind direction does not cause the AEP analysis to fail.

**Comment by nbodini** [comment]
Hi @ejsimley , I've now tried to run the example and everything seems to be fine with the current version of plant_analysis.py.

**Comment by jordanperr** [comment]
@ejsimley can you confirm this has been resolved?

**Comment by ejsimley** [comment]
@jordanperr yes, this issue no longer shows up after Nicola's latest PRs. We should probably merge this into master soon to fix the issue there too.
