### ISSUE TITLE
IEC Power Curve Not Behaving As Expected

### ISSUE THREAD

**Issue by RHammond2** [NREL/OpenOA#133]
https://github.com/NREL/OpenOA/blob/6bed784a50cb223386fce38afb1929365faa8f90/operational_analysis/toolkits/power_curve/functions.py#L13-L51

I was using the IEC power curve function, but found that the `windspeed_end` input does not always translate to a cutoff speed at which all power output is zero above a certain windspeed. There are a variety of different ways that it goes wrong, but I have found that in order for it to work correctly, the provided `windspeed_column` and `power_column` must have a zero power input as the last entry that corresponds to windspeed that is two `bin_width`s after the last windspeed.

This means that if `bin_width=0.5` and the last power-producing windspeed is 25m/s, then the windspeed entry corresponding to 0kWh must be 26m/s. If the the last windspeed and power combination is defined in any other way, then the power curve function returns a non-zero value for all windspeeds greater than 25m/s.

**Comment by jordanperr** [comment]
Fixed with pr #134
