### ISSUE TITLE
python_requires='3.6,3.7,3.8'

### ISSUE THREAD

**Issue by apaullier** [NREL/OpenOA#135]
In the **setup.py** script, the line containing `python_requires='3.6,3.7,3.8'` is causing installation problems.  Specifically, it rises the following error:
```
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y7/w6k8yt492317ll3rqlp2p45h0000gp/T/pip-req-build-gm8ir7dh/setup.py'"'"'; __file__='"'"'/private/var/folders/y7/w6k8yt492317ll3rqlp2p45h0000gp/T/pip-req-build-gm8ir7dh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/y7/w6k8yt492317ll3rqlp2p45h0000gp/T/pip-req-build-gm8ir7dh/
    Complete output (1 lines):
    error in OpenOA setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '3.6'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Changing that line to --> `python_requires='>=3.6'` solves the issue.

I believe it must have been changed on the latest release due to dependencies problems with **Shapely**, which does not yet have binary wheels in pip for Python 3.9 on Mac.

Maybe by changing it to a different syntax may solve the issue. Maybe `python_requires='>=3.6, <3.9'`?

[python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)

**Comment by jordanperr** [comment]
Hi @apaullier, and thank you for reporting this issue. It is curious that the issue doesn't seem to affect my own installation of OpenOA, nor any of the automated tests here with Github Actions. Looks like there is an open bug report for this issue in Python packaging: https://github.com/pypa/packaging/issues/107

I like your suggestion to implement the requirement as `python_requires='>=3.6, <3.9'` and would be happy to accept a pull request with this change. Please let me know if you run into any issues or if you would like more guidance on how to submit a pull request.

**Comment by jordanperr** [comment]
This is being taken care of in pull request #128 . Thank you for reporting this bug!
