### ISSUE TITLE
Update setup.py "python_requires" details

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#140]
The current python_requires syntax in setup.py does not appear to work for me. When I try "pip install ./OpenOA" I get the following error:

_error in OpenOA setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '3.6'_

I suggest updating to: python_requires='>=3.6,<=3.8.8' in the setup.py

Should I try this out as the most basic of pull requests??

**Comment by jordanperr** [comment]
Thank you so much for reporting this issue. The issue was reported before with Issue #135 and was merged into the develop branch with PR #128. It is probably time to make a new release from Develop! Closing this issue for now.
