### ISSUE TITLE
Project Engie AssetData is missing

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#145]
The asset/[static data](https://opendata-renewables.engie.com/explore/dataset/6eeb7f50-97f7-4ab2-8d36-c6d9f9491d84/information) for "Project Engie" has not been included in the example model. Its also unclear to me what the AssetData should/can contain (e.g. id, type, geometry), despite having some functions that operate on this data. I'd find it helpful to have a clear description of the minimal requirements for this data.

**Comment by ejsimley** [comment]
Thanks for pointing this out @charlie9578. We havn't needed asset data for any examples yet, so didn't include any data. But this should be fixed. I'm working on getting an asset data file added to the examples folder and imported using the `Project_Engie` prepare method.

**Comment by ejsimley** [comment]
As we discussed, asset data has been added to the example project. We still need to improve documentation of the required asset data variables. For now, information for fields that are currently used can be found in `operational_analysis/types/plant_schema.json`
