### ISSUE TITLE
Create a wind farm map based on the project-asset information

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#149]
I'd like to see some additional plotting tools for analysts to use, so we can better understand the assets. As a starter I'm proposing to add a wind farm map using the project-asset data. A couple of things I'd like to check:

1. Is it okay to add the function to the pandas_plotting.py toolkit?
2. Is it okay to use the [bokeh library](https://docs.bokeh.org/en/latest/index.html)? I can add it to the requirements
3. Is it okay to add an example to the first [Example notebook](https://openoa.readthedocs.io/en/latest/examplesout.html#Import-the-data), to highlight the asset data, above the turbine list output?

**Comment by ejsimley** [comment]
Charlie, glad that we could merge in your wind farm map plotting contribution, thanks so much for your work on that! Is it OK to close this issue? Also, happy to discuss other feature ideas you're interested in sometime.

**Comment by charlie9578** [comment]
Hi Eric, glad to see the maps now included! So yes, safe to close. I'll have a think about what to work on next. Thanks, Charlie
