### ISSUE TITLE
Saving the project fails where not all tables are defined

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#151]
Saving the project fails where not all tables are defined, as the dataframes do not exist. For example, where tower data has not been included, when saving the project the following error is thrown: AttributeError: 'NoneType' object has no attribute 'to_csv'

```
from project_ENGIE import Project_Engie

project = Project_Engie('./data/la_haute_borne')
project.prepare()

project.save('data2')
```

Should empty dataframes be created as part of the PlantData init? Or PlantData tables only be created if data is available to load in? Or save be designed to handle empty dataframes? I'm happy to propose a solution based on the prefered approach.

**Comment by jordanperr** [comment]
As discussed - We will make the save() and load() functions more flexible to allow for missing timeseries tables.

**Comment by charlie9578** [comment]
I'll provide a quick fix for this in the near future, as I've been having a play again

**Comment by jordanperr** [comment]
Closing this as we no longer have save and load methods in PlantData V3.
