### ISSUE TITLE
Use ENGIEs open data windfarm as example data set

### ISSUE THREAD

**Issue by sebastianpfaffel** [NREL/OpenOA#17]
The ENGIE open data windfarm seems to be a good data set to test and demonstrate the capabilities of OpenOA while using publicly available data. Thus, I'd like to add an example of how to import turbine data from this source into OpenOA and create an additional class similar to the TurbineExampleProject class. 

Furthermore, I'd either like to edit the "Turbine Level Toolkit Notebook" example in the docs to use the ENGIE data instead of the CSV file or just add the info of hot to use it as an alternative data source to the same notebook. Any opinions on that?

**Comment by moptis** [comment]
@sebastianpfaffel  I am in support of this idea. Would the Engie data need to be hosted here, or can it be accessed through an API? The latter would be obviously advantageous.

**Comment by sebastianpfaffel** [comment]
@moptis Thanks for your reply. The data is hosted by Engie and available on https://opendata-renewables.engie.com/ for a manual download of through an HTTP REST API. Thus it can be directly loaded by a python script and doesn't need to be hosted by OpenOA. I have some first code ready and will create a PR as soon as I have examples ready as well.

**Comment by sebastianpfaffel** [comment]
I finally found some time to finish the import script and edit the example in the ipnb. Would be great if someone can review it. We could get rid of the csv file, but someone would need to find a period with more outliers in the ENGIE data. #22

**Comment by sebastianpfaffel** [comment]
Thanks for your review and merging!
