### ISSUE TITLE
Binder instance broken (error log below)

### ISSUE THREAD

**Issue by Dynorat** [NREL/OpenOA#185]
When trying to run example notebooks in binder the process fails. See below for issue log.

Issue log below
--------------------------------------
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker1_y8_h4a'...
HEAD is now at 10b9408 V2.3 (#182)
Building conda environment for python=3.7Using PythonBuildPack builder
Building conda environment for python=3.7Building conda environment for python=3.7Step 1/52 : FROM buildpack-deps:bionic
 ---> 043b5581e482
Step 2/52 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 92fb6ec34267
Step 3/52 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2d6459a59002
Step 4/52 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> df71e0e05b39
Step 5/52 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 34e81d56d636
Step 6/52 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 6adfb5b9779a
Step 7/52 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 8bb736eaf17e
Step 8/52 : ENV SHELL /bin/bash
 ---> Using cache
 ---> 681a40b0bfac
Step 9/52 : ARG NB_USER
 ---> Using cache
 ---> d163a1842b28
Step 10/52 : ARG NB_UID
 ---> Using cache
 ---> 8e68e6f32df7
Step 11/52 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 2437b5d50348
Step 12/52 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> a02eb9e3237c
Step 13/52 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> 09f283666c0e
Step 14/52 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 320e984081fb
Step 15/52 : EXPOSE 8888
 ---> Using cache
 ---> f38097b63171
Step 16/52 : ENV APP_BASE /srv
 ---> Using cache
 ---> 7eef829f1736
Step 17/52 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> 64216ab9d798
Step 18/52 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> 8ef70b26af06
Step 19/52 : ENV NPM_DIR ${APP_BASE}/npm
 ---> Using cache
 ---> d38553a60eb5
Step 20/52 : ENV NPM_CONFIG_GLOBALCONFIG ${NPM_DIR}/npmrc
 ---> Using cache
 ---> bfdc6d0db0ba
Step 21/52 : ENV NB_ENVIRONMENT_FILE /tmp/env/environment.lock
 ---> Using cache
 ---> b52f3ea6881f
Step 22/52 : ENV MAMBA_ROOT_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> 5e415274686f
Step 23/52 : ENV MAMBA_EXE ${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> 1791bfffb627
Step 24/52 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> 0b1f72f91340
Step 25/52 : ENV PATH ${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> 00ba87159ee9
Step 26/52 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-391af5 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> f34e9eac748e
Step 27/52 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e7-2elock-4f1154 /tmp/env/environment.lock
 ---> Using cache
 ---> 4a570488d15c
Step 28/52 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-8fbb20 /tmp/install-base-env.bash
 ---> Using cache
 ---> 91a9cb12454b
Step 29/52 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Using cache
 ---> ad17bb41de53
Step 30/52 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> dbff75f14752
Step 31/52 : USER root
 ---> Using cache
 ---> 4850870365ad
Step 32/52 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> 09ad80ada02b
Step 33/52 : ENV REPO_DIR ${REPO_DIR}
 ---> Using cache
 ---> 1d7fe8195f02
Step 34/52 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> bae950312242
Step 35/52 : RUN chown ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Using cache
 ---> 2dc63f064163
Step 36/52 : ENV PATH ${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> c384b743c66c
Step 37/52 : ENV CONDA_DEFAULT_ENV ${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> b57577c1c588
Step 38/52 : COPY --chown=1000:1000 src/requirements.txt ${REPO_DIR}/requirements.txt
 ---> 87b0f1aec0d1
Step 39/52 : USER root
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in 8fa7017595e0
Removing intermediate container 8fa7017595e0
 ---> ba4270033d12
Step 40/52 : COPY --chown=1000:1000 src/ ${REPO_DIR}
 ---> db8757da8ab2
Step 41/52 : USER ${NB_USER}
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in 7f5d063759f3
Removing intermediate container 7f5d063759f3
 ---> c08eceafeee4
Step 42/52 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in 1c9ab77e7839
Collecting eia-python==1.22
  Downloading eia_python-1.22-py3-none-any.whl (3.8 kB)
[91mERROR: Could not find a version that satisfies the requirement pyproj==3.3.* (from versions: 1.8.0, 1.8.1a0, 1.8.1, 1.9.3, 1.9.4, 1.9.5, 1.9.5.1, 1.9.6, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.2.post1, 2.5.0, 2.6.0, 2.6.1, 2.6.1.post1, 3.0.dev0, 3.0.dev1, 3.0.dev2, 3.0.dev3, 3.0rc2, 3.0.0, 3.0.0.post1, 3.0.1, 3.1.0, 3.2.0, 3.2.1)
ERROR: No matching distribution found for pyproj==3.3.*
[0mRemoving intermediate container 1c9ab77e7839
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 1Built image, launching...
Failed to connect to event stream

**Comment by jordanperr** [comment]
Fixed in PR #186
