### ISSUE TITLE
ERA5/MERRA2 - PlanetOS Datahub is closing

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#187]
For accessing ERA5/MERRA2 we might need a new method going forward, as the Planet OS Datahub appears to be closing. I'm not sure if the (PlanetOS) AWS databases will continue to be updated. If so then we could access that directly using boto, which is pretty straight forward - although the data dimensions are still not the best for our use case. See [era5-s3-via-boto.ipynb](https://github.com/planet-os/notebooks/blob/master/api-examples/era5-s3-via-boto.ipynb)

> Hi,
> 
> We are sorry to let you know that we will shut down the Planet OS Datahub on August 8th 2022. 
> 
> We wish you all the best in finding another source for your weather data. Please let us know if there are any concerns or if we can help you in any way. For more information on Intertrust's other products, please visit [www.intertrust.com](www.intertrust.com). 
> 
> It was pleasure to provide you with data for all these years. Thank you. 
> 
> Kind wishes,
> 
> The Planet OS team

**Comment by jordanperr** [comment]
Plan is to remove the PlanetOS code from V2.3 by August 8th and find a suitable data source for V3.

**Comment by charlie9578** [comment]
Within the [feature/cubico-projects](https://github.com/charlie9578/OpenOA/tree/feature/cubico-projects) branch I've added a simple downloader for monthly era5 data, which could be used as a stop-gap until something more robust is in place. 

The downloader could be used for hourly data too, but would take an age to download, hence I stuck to the monthly data, which takes about 30mins for 20 years of data.

**Comment by charlie9578** [comment]
The [feature/cubico-projects](https://github.com/charlie9578/OpenOA/tree/feature/cubico-projects) branch now includes a downloader for monthly merra2 data as well

**Comment by jordanperr** [comment]
@ejsimley can this issue be closed?
