### ISSUE TITLE
Feature enhancement - new "project" examples for Kelmarsh and Penmanshiel

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#188]
I'd like to make it easy for people to use the data we've recently released from Kelmarsh and Penmanshiel wind farms in OpenOA. 

I've created a Project_Kelmarsh similar to Project_ENGIE, and managed to run everything, but I'm thinking it would be better to use the save/load functions and have projects available on [Zenodo](https://zenodo.org/record/5841834) in the OpenOA format ready for loading. Then make this a fairly generic load, so that as more open data sets become available they can be downloaded and easily read into OpenOA.

I'll have a play and then share my proposal for review.

Thanks, Charlie

**Comment by charlie9578** [comment]
Hi Eric, yeah that sounds good. I'll check out the V3 develop branch and see about using it with the two wind farms. I'm on holiday the first week of June, but would be free on 7th June onwards. Sounds like a positive development though :) Thanks, Charlie

**Comment by charlie9578** [comment]
Hi, 

I've had a go at adding Kelmarsh and Penmanshiel to OpenOA and I think I've got things working smoothly now. Its accessible [here](https://github.com/charlie9578/OpenOA/tree/feature/cubico-projects). Some features:

1. Automatically downloads and unzips the data from Zenodo
2. Automatically downloads monthly ERA5 data for the sites from CDS (registration required)
3. Simple switching between assets in the 02_plant_aep_analysis_cubico notebook
4. It uses the V3 API
5. It runs! (...at least on my PC... and yes... I'm claiming that as a feature!)

@ejsimley would you be able to review and suggest what the next step(s) should be to get this integrated into OpenOA?

Thanks,
Charlie

**Comment by ejsimley** [comment]
Hi @charlie9578 thanks so much for adding the two wind plants as examples in OpenOA V3! After a quick read through, it looks nice. I'll run the example this week and discuss with the rest of the team, and get back to you with any comments or ideas.

**Comment by charlie9578** [comment]
Hi, 

I've just updated it so that MERRA2 monthly data can also be automatically downloaded (registration also required). I'm thinking perhaps these download tools should live somewhere else though, rather than directly in the project_Cubico script, as they are likely to be useful for others.

Thanks,
Charlie

**Comment by ejsimley** [comment]
pull request #222 merged
