### ISSUE TITLE
Division by zero error/warning in L5P power curve

### ISSUE THREAD

**Issue by sebastianpfaffel** [NREL/OpenOA#21]
The L5P power curve returns an error/warning if you query the power value for a wind speed of 0. 

`x = np.linspace(0,20,100)`
....
`plt.plot(x, l5p_curve(x), color="C2", label = 'L5P', linewidth = 3)`

> --> parametric_forms.py:35: RuntimeWarning: divide by zero encountered in power
>   return d + (a - d) / (1 + (x / c) ** b) ** g

**Comment by jordanperr** [comment]
I've encountered this warning before and have spent a little time playing around with it. I was not able to find a robust solution aside from simply silencing the warning, which I decided not to do.

**Comment by sebastianpfaffel** [comment]
Okay, I spend a little time, actually way too much time, looking into this. 

The issue is the "(x / c) ** b" part. b is bound to be negative in the fitting algorithm. Thus we always have a 1/(x/c)**-b situation. When x is 0 it leads to 1/0. 

We have three options:
1. We decide to ignore it and catch the warning. In this case, numpy assumes 1/0 to be 1/0.000......1 and thus inf. In our case this is fine and the result is as close as it gets to what we'd expect it to be.
2. We replace x=0 knowingly by a very small number e.g. 0.00001 using  np.where(x!=0,x,0.000001) and end up with the same result.
`def logistic5param(x, a, b, c, d, g):
    return d + (a - d) / (1 + ( np.where(x!=0,x,0.000001) / c) ** b) ** g `
3. We define the function to return a power of zero at a wind speed of zero. This might lead to unwanted results in case of weird measurements though and is only valid for the purpose of a power curve. We still need to avoid the warning beforehand.
`def logistic5param(x, a, b, c, d, g):
    return np.where(x != 0,
        d + (a - d) / (1 + np.power((x / c), b,where=x!=0)) ** g 
        ,0)`

I'm a little indecisive regarding our options but would tend either to option 1. or option 3. while favoring option 3. It's always nice to start with a 0;0 for a power curve. It's honestly not a very important issue but since we discussed it already I'd like to resolve it. Definitely looks better in the examples.

Any opinions which way to go?

**Comment by moptis** [comment]
@sebastianpfaffel 

Good catch, and thanks for looking into this!

The problem with option 3 is that many turbines we look at report parasitic power at low wind speeds (e.g., negative power, or power used to keep turbine electrical systems online, etc.). Assuming zero wind speed is zero power could mess up the power curve if we wanted to preserve that parasitic power relationship.

I tend to favor #1 as the fix.

On another note, I don't think the logistic 5 generalized well. The parameter 'a' takes bounds of (1200, 1800) which is based on the turbine capacity on which this function was originally built (i.e. 1.7 MW). The analyst who wrote this function has since left NREL. To allow this function to generalize as other turbines, either we need to add a 'turbine_capacity' parameter and scale 'a' to somewhere around 90-110% of that capacity, or we let the user specify the bounds. This can be a seperate ticket, of course.

**Comment by sebastianpfaffel** [comment]
@moptis 
I thought about the issue of bad data/measurements but came to the conclusion that such data would probably be filtered out beforehand anyway. It's actually only a plotting issue, real wind speeds of zero shouldn't appear. Thus I'm also good to go with solution -1 or -2. The benefit of -2 would be a behavior we actually understand. Honestly, I don't know what kind of black magic numpy does internally ;) Either way I can look into it and provide a PR and also fix the second issue you mentioned.

My approach would be to edit the "fit_parametric_power_curve" as suggested and provide inputs based on the maximum power values from the data set. This function would probably fit into "logistic_5_parametric" function.

**Comment by jordanperr** [comment]
We are talking about power curves here - not the measured power output of the wind turbine. Is there any case where the *power curve* itself should report a non-zero power when the windspeed is zero? If not (and I don't see why not), then option 3 seems like the obvious choice to me.

**Comment by jordanperr** [comment]
@moptis @sebastianpfaffel I don't think we ever came to a consensus on this issue. I think we have all eschewed option 2 in favor of either 1 or 3. I strongly prefer option 3.

It would seem that a negative power at 0 could be handled by the "d" parameter, which would be negative in this situation?

Where x!=0:
- d + (a - d) / (1 + (x / c) ** b) ** g
Where x==0:
- d

**Comment by sebastianpfaffel** [comment]
Option 3. is the preferable solution for me as well and I'm happy to create the corresponding PR. 

I didn't really get what you were describing here. Can you elaborate on that?
> It would seem that a negative power at 0 could be handled by the "d" parameter, which would be negative in this situation?
> 
> Where x!=0:
> 
>     * d + (a - d) / (1 + (x / c) ** b) ** g
> 
> 
> Where x==0:
> 
>     * d

**Comment by jordanperr** [comment]
@sebastianpfaffel @moptis, I have created a pull request that implements the behavior described in my last comment: #75 
I will close this issue and we can move the discussion to there.
