### ISSUE TITLE
add OpenOA to DOE code index

### ISSUE THREAD

**Issue by Dynorat** [NREL/OpenOA#213]
Suggest adding OpenOA to DOE code index to make it more FAIR.  https://www.osti.gov/doecode/

**Comment by jordanperr** [comment]
OpenOA is already listed on osti.gov, and it links to this Github repository. It was my understanding that this listing (created from the NREL Software Record) puts OpenOA in the appropriate indexes.

https://www.osti.gov/biblio/1478526

**Comment by Dynorat** [comment]
submitted to DOE code index on May 4, 2023

Project 105853

**Comment by Dynorat** [comment]
Actually submission is hanging.  All metadata is saved in their system.  Have sent an email to tech support for assistance.

**Comment by Dynorat** [comment]
Already added to DOEcode previously: https://www.osti.gov/doecode/biblio/19927
