### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by RHammond2** [NREL/OpenOA#214]
This issue is a reflection of the unaddressed content improvements from @jordanperr and @ejsimley in #207.

- [x] Add more user-friendly information to the Overview section of `sphinx/index.rst`
- [x] Introduce more of the code in the Overview section of `sphinx/index.rst` (@ejsimley)
  - The Overview section would be a good place to describe all of the analysis methods at a high level and the utils toolkits as well, so that the "Plant Data", "Analysis Methods", and "Utils" pages on the top menu make more sense. This way users can understand what OpenOA can be used for. I can work on this. And then the order of the pages in the table of contents/menu might make more sense as plant data, analysis methods, utils, then examples since Plant Data is at the core of all things OpenOA, then analysis methods are the most important high-level methods, followed by utils, with examples I think making sense after the software components are explained.
- [x] Improve the readability of the installation and contributing sections
- [x] Provide a better introduction to the examples in `sphinx/examples/index.rst`
- [x] The reanalysis section of `sphinx/api/types.rst` needs to be rewritten to be more sensible and applicable to users
- [x] Rethink the section titling for the `sphinx/api/analysis.rst` and if we want more description in the RST file for each of the analysis categories (or methods) or just to modify the docstring content that populates these pages
- [x] Link to our analysis papers that helped develop these methods or utilized these methods (should we feature other papers too?--this could be a good way to engage the community and highlight their work that uses the code @ejsimley or @jordanperr or @Dynorat thoughts on this part would be good)

**Comment by ejsimley** [comment]
When looking at the new documentation I noticed that example 2b is not included in the examples documentation. Should this be added, or is there a reason it isn't included yet?

**Comment by RHammond2** [comment]
It was intentional but only because it hadn't been  updated with example 2, so I was unsure if it should be included or not. Happy to bring up to date and reinstate it though.

**Comment by jordanperr** [comment]
Additionally, it would be nice to have some tables or lists in the documentation showing the tag names, units, frequencies, and any other requirements, broken out by analysis type.

We could also compile a superset of all possible columns into one large schema document.

I suggest this all be defined in JSON files somewhere (such as an Analysis_Requirements JSON file, and a PlantSchema JSON file), which is then read in by Sphinx to generate the tables automatically. Related to #227
