### ISSUE TITLE
h5pyd is included in qa.py but not present in setup.py dependencies list

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#220]
When installing OpenOA V3 (from develop_v3 branch) in a new environment, upon first run of the example 00_intro notebook, user is greeted with an error that h5pyd can not be found.

Solution:
- User can run `pip install h5pyd` and reload the notebook kernel.

Proposed action:
- Add h5pyd to dependencies, or remove import from the top of qa.py 

References:
- https://github.com/NREL/OpenOA/blob/319cf16c545a766fb897e7ceb27b678401c294fc/openoa/utils/qa.py#L9

**Comment by RHammond2** [comment]
Thanks for catching this. I think in the old version of the QA notebook, the message about needing h5pyd and running `pip install "openoa[wtk]"` was more prevalent, but we could certainly move this single requirement into the develop category in the setup script: https://github.com/NREL/OpenOA/blob/develop_v3/setup.py#L34-L56.

**Comment by ejsimley** [comment]
This issue is addressed in PR #218 where h5pyd is added as a dependency in setup.py and requirements.txt
