### ISSUE TITLE
Understand root cause of GBM and Wake Losses analysis regressions due to Pandas and Scikit-Learn updates.

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#239]
In https://github.com/NREL/OpenOA/pull/226 , we tried to understand why certain regression tests failed when updating Pandas and Scikit-Learn. We were unable to fully identify the root cause and made a decision at the time to simply updated the regression tests for now. Before the release is made, it is imperative to better describe and understand the root cause of these regressions, and update the AEP GBM and Wake Losses modules so it doesn't happen again in the future.

- Understand and describe the root cause of the regressions.
- Update the affected analysis modules.
- Add unit tests to ensure regressions like this are easier to debug in the future.

**Comment by RHammond2** [comment]
At this stage, I believe we've just accepted the differences with no pushback on results discrepancies, so I'm closing this, though the stability of these tests has long been an unresolved issue.
