### ISSUE TITLE
UI Improvements in Jupyter

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#242]
Would be nice to have a better UI in jupyter notebooks for plantdata. For example, when you currently display the plantdata it prints out a bunch of text which is hard to interpret. Would be nice to detect when running in an ipython kernel through jupyter, and display rich HTML.

**Comment by RHammond2** [comment]
@jordanperr  would you consider this closed with #248?

**Comment by jordanperr** [comment]
Yes!
