### ISSUE TITLE
Review logging statements

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#243]
Ensure that loggers are implemented in the analysis classes and on any modifications to plantdata. This is important for analysts to be able to track which cleaning steps have been performed before analysis, and to log the options which were provided to each analysis.

**Comment by RHammond2** [comment]
Based on #246, we should also be reviewing the ML pipeline logging, per your comment [here](https://github.com/NREL/OpenOA/pull/246#discussion_r1312362017).
