### ISSUE TITLE
Review package requirements in setup.py

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#259]
The requirements in setup.py have become out of date and have too many extra dependencies in the core requrirements.

Some clear places to start:
- pyspark, not required anymore
- jupyterlab, review if still needed or move to an extra
- statsmodels is in there twice
- dask, review if still required

- Hex is pinned to numpy 0.23, but we require 0.24. Is there a reason to require 0.24?

**Comment by RHammond2** [comment]
Here is the complete roundup from our discussion last week:

- [ ] update `attrs` to `attrs>=22.2`
- [ ] add `ipython` as a first class dependency
- [ ] remove duplicated `statsmodel`
- [ ] remove `pyspark`
- [ ] remove `examples/requirements.txt`
- Add the following install options:
  - [ ] add a note to the appropriate sections in the documentation indicating these updates
  - [ ] examples
    - `jupyterlab`
  - [ ] reanalysis
    - `cdsapi`
    - `xarray`
    - `netcdf4`
    - [ ] Add a note to the Cubico example stating this option will need to be installed first
  - [ ] nrel-wind (or similar naming)
    - `h5pyd` (wind toolkit)

**Comment by RHammond2** [comment]
It turns out that Dask is required for xarray to load in the reanalysis data, so I've updated xarray to be `xarray[parallel]` to be up to xarrays spec on that front, rather than managing it separately.

**Comment by RHammond2** [comment]
This was addressed in #262, and once merged into main, will be closed.
