### ISSUE TITLE
Cubico example notebook data download fails

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#263]
While running the example notebook **02b_plant_aep_analysis_cubico.ipynb** i ran into the following issues:

1. SSL error downloading data when on VPN.
2. Even when off VPN, downloading is slow and the progress isn't clearly reported.
3. The download eventually fails with `Missing/incomplete configuration file: /home/vscode/.cdsapirc`

**Comment by RHammond2** [comment]
Would adding an important alert at the top of the cell indicating that a registration is required for both the CDS and MERRA2 data be helpful? This would essentially restate the content of "Step 1", but higher up and be much harder to miss.

**Comment by jordanperr** [comment]
Adding a warning box might be a good idea. But as this is expected behavior I will close the issue.
