### ISSUE TITLE
readthedocs - functions not shown in sidebar for PlantData API

### ISSUE THREAD

**Issue by charlie9578** [NREL/OpenOA#278]
Hi, this one is just a small comment, but the PlantData API functions aren't shown in the righthand sidebar, while they are for the Analysis Methods and Utils (although formating varies). Is there a reason behind this? I'd prefer to see the full list of functions, as it makes finding them easier. Thanks

![image](https://github.com/NREL/OpenOA/assets/14888896/5ee53e3e-50ce-4e22-978c-c708b8d93d27)

![image](https://github.com/NREL/OpenOA/assets/14888896/d8770597-e680-4be7-9fe4-d3af1f591188)

**Comment by RHammond2** [comment]
Thanks for flagging this @charlie9578, I'll see if I can get a fix into your v3.1 release that's coming later this week if all goes according to plan.

**Comment by RHammond2** [comment]
You should be able to see the results in the [PR docs build site](https://openoa--267.org.readthedocs.build/en/267/api/types.html#plantdata-api). Please let us know if there's anything else that doesn't look quite right!

**Comment by RHammond2** [comment]
@charlie9578 I've made some updates in the v3.1 release, does this satisfy what you were looking for? If so, feel free to close the issue, otherwise we can keep working towards a resolution.

**Comment by charlie9578** [comment]
Hi, looks good. Thanks for the quick fix!
