### ISSUE TITLE
Dataset issue for the analysis

### ISSUE THREAD

**Issue by ajayxcel** [NREL/OpenOA#285]
Hi OpenOA team,

I have been trying to use your code for my datasets. I'm facing lot of errors. I'm following the exact formatting as in your example files but I could not get merra2 and era5 data same as in your files. So, I have created dummy data for what's missing. I'm facing errors mostly with the 'reanalysis' of era and merra with MonteCarloAEP. Is it going to check the integrity of my data as well? Is it because I'm using dummy data and some of the validation tests in the background throwing the error? I'm not sure, the same data sets work for some example code and do not work for other codes. Could you help me with the exact formatting of the datasets? Do you have any document explaining that? Also, could you help me with the sources where I can find merra and era data same like your csv files?

I'll be waiting for your response. I really appreciate your help!

Thanks,
Ajay

**Comment by RHammond2** [comment]
Hi @ajayxcel, thanks for reaching out! The checks performed against the data are going to be as follows:
- Are all the required columns present?
- Do the columns adhere to the correct to the expected data types, or can they be converted to them?
- Is the frequency of the data aligning with the expectations specified in the metadata?
- Does the frequency of the data adhere to the required frequency options for the analysis type?

I'm not sure if you've poked around our documentation at all, but the [PlantData and PlantMetaData data specifications](https://openoa.readthedocs.io/en/latest/api/schema.html#merra-2) should help, alongside the [descriptive schemas](https://github.com/NREL/OpenOA/tree/main/openoa/schema) in the repository (the README provides a bit of background).

As for where to get the data, there is a bit of info at the top of our [`utils/downloader.py` module](https://github.com/NREL/OpenOA/blob/main/openoa/utils/downloader.py) about the souces for both that I'd point you to first. Just note, that if you do use our interface for downloading them (as is done in the Cubico example script), be sure to install with the `renalysis` installation option.

Let me know if this helps!

**Comment by ajayxcel** [comment]
Thank you very much for the reply. That was really helpful. By the way, I couldn't find density data for merra2. Are we suppose to calculate it or using the 'downloader.py' gets all the data for me? Thanks again!

**Comment by RHammond2** [comment]
Glad that was able to get you squared away for the most part. You can also calculate the density using our `utils/met_data_processing.py` module, specifically the [`compute_air_density`](https://github.com/NREL/OpenOA/blob/bcac071c08b69033da73c336fd7193db55ec3fe0/openoa/utils/met_data_processing.py#L127) method ([documentation link](https://openoa.readthedocs.io/en/latest/api/utils.html#openoa.utils.met_data_processing.compute_air_density)).

As for the MERRA2 and ERA5 files, be sure to check your date ranges, frequency, and geographic area as these have the largest influence on file size. For instance an hourly profile for 20 years and monthly profile for 20 years will be quite different in scale, just as an hourly profile for one coordinate will be much smaller than capturing the surrounding region of a few sites.

**Comment by ajayxcel** [comment]
Thank you very much for your help sir. Your answers were useful for me. I have a small request. Most of the errors I face are mostly due to the dataset and formatting. If possible, could you create a section somewhere in the documentation on formatting conditions for the input csv files? Example, the range of data to be used, formatting of columns, number of turbines to be input, etc.

Thanks again! I really appreciate your help.
