### ISSUE TITLE
OpenOA not installed by pip install openOA

### ISSUE THREAD

**Issue by jtremesay** [NREL/OpenOA#287]
Hi!

Is there a reason why `pip install OpenOA` installs all the stuff (deps, docs, examples, …) but not the package himself?

**Comment by RHammond2** [comment]
Hi @jtremesay, typically this should be the other way around in a pip install, could you provide more details around your installation steps and the exact issue you're having? A traceback error relating to the issue would also be really helpful to understand what exactly is happening.

**Comment by RHammond2** [comment]
I think I may have come across your issue when working with a fresh environment and workflow. Please see if version 3.1.1 resolves this issue for you and let me know.

**Comment by jtremesay** [comment]
My initial issue :

```shell
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install OpenOA==3.1.0
$ python -c "import openoa; print(openoa.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'openoa'
```

I was not sure if that was a real issue or a voluntary choice on your part :) 


Work as expected with 3.1.1
