### ISSUE TITLE
Add nbconvert to documentation build process

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#29]
Currently we must re-build the rst files from the example notebooks manally, using a command like `jupyter nbconvert --to rst examples/.../notebook.ipynb` and then copy the generated files into `sphinx/`. It would be nice to automate this process as part of the sphinx makefile.

- Add command like `make examples` to the sphinx makefile
- Ensure this works with readthedocs.io

**Comment by sebastianpfaffel** [comment]
@jordanperr 
I created a pull request using nbspinx and nbmerge. Looking forward for your review.
