### ISSUE TITLE
Question on windiness correction plot

### ISSUE THREAD

**Issue by ajayxcel** [NREL/OpenOA#292]
![download](https://github.com/NREL/OpenOA/assets/164583519/8fe97d78-a145-4893-a56c-ee2cef189813)
Hi @RHammond2 , 
Good morning! I have a question on one of the plots in the example code 02a_plant_aep_analysis. In the windiness correction plot, what is 'Individual AEP Estimates'? Is that representing random estimates from MonteCarlo OA? I have attached the plot image for reference.
Thank you!

**Comment by RHammond2** [comment]
Hi @ajayxcel, the "Inidividual AEP Estimates" are estimates from individual simulations. Here, we're looking at how they vary by number of years in the windiness correction, but this could be broken out by any of the variables that were measured for uncertainty.
