### ISSUE TITLE
Add NaN/None filter to filters.range_flag

### ISSUE THREAD

**Issue by sebastianpfaffel** [NREL/OpenOA#34]
As far as I can tell, OpenOA doesn't provide an option to filter NaN or None values in the turbine data yet. In my opinion, this functionality should be part of the range_flagging filter. I'd expect the filter to flag all NaN and None values as well and allow to keep only valid values in my defined range. 

Alternatively, there could be an additional function for this. Opinions?

**Comment by jordanperr** [comment]
How about we switch range flag to return the negation of an inclusive internal range, a-la:

flag = !((data_col <= below) | (data_col >= above))  # Apply the range flag

**Comment by sebastianpfaffel** [comment]
> 
> 
> How about we switch range flag to return the negation of an inclusive internal range, a-la:
> 
> flag = !((data_col <= below) | (data_col >= above)) # Apply the range flag

Yes, more or less. If we use a negation we must also replace below and above and use and instead of or. I'll open a PR. 

flag = ~((data_col <= above) & (data_col >= below)) # Apply the range flag
