### ISSUE TITLE
Confusing behavior of filters.range_flag

### ISSUE THREAD

**Issue by sebastianpfaffel** [NREL/OpenOA#35]
I find the behavior of the filters.range_flag function a little confusing. 

It asks for the arguments **below** and **above** to select outliers but what it does is:
`   flag = ((data_col <= below) | (data_col >= above))  # Apply the range flag`

Thus the code from the example would flag wind speeds of 0.
`filters.range_flag(windspeed, below=0, above=70)`

I'd like to change the flagging to: 
`   flag = ((data_col < below) | (data_col > above))  # Apply the range flag`

Is there any reason to keep it as it is rn?

**Comment by moptis** [comment]
@sebastianpfaffel I'd support this change. Makes sense to me.

**Comment by sebastianpfaffel** [comment]
Alright I've created the corresponding PR.
