### ISSUE TITLE
Factor out WTK dependence from QC method

### ISSUE THREAD

**Issue by moptis** [NREL/OpenOA#48]
QC method currently depends on WTK framework. We should factor WTK out into its own class, similar to what was done for reanalysis.

**Comment by ejsimley** [comment]
Some ideas:
-Agree it makes sense to factor the wind resource interface into a separate class
-Consider adding WTK interface to the ReanalysisData class and include QC-related methods in ReanalysisData
-Include ERA5 as an option for project sites outside of North America
-Can we use the era5 api to interface with ERA5 data for the QC methods? (https://github.com/coecms/era5)

**Comment by Dynorat** [comment]
Here is a potential package for ERA5 data which is global: https://github.com/coecms/era5

**Comment by moptis** [comment]
Hey all, before heading down that ERA5 route, not that I have a script on Eagle that grabs 100m ERA5 data globally, which is then processed in my reanalysis_data repo on the internal GitHub. I can demonstrate the code at the next stand-up if interested. I believe Joseph has used it before.

**Comment by ejsimley** [comment]
Hey Mike, that would be great if you want to demonstrate that code at the next meeting. We can discuss which method for accessing the ERA5 data would be easiest to include in the QC process.

**Comment by moptis** [comment]
Sounds good. I might advise against using a reanalysis product in the QC process though. WTK was used to determine the timezone of the wind plant data by plotting diurnal means of both the wind plant and WTK data. The problem with reanalysis data is that it's not great at capturing the diurnal cycle near the surface, so it might mislead the QC process. Maybe ERA5 is better at that now, but I remember MERRA-2 could be like 2-3 hours off. WTK on the other hand was accurate.

**Comment by jordanperr** [comment]
IIRC the motivation for this ticket was to enable the qc class to function outside of the WTK's domain (e.g., Europe). Is this correct, @moptis?

**Comment by moptis** [comment]
Yup, that was the idea. I'm just not sure reanalysis data is the answer. For Europe, you could use the New European Wind Atlas, which is based on WRF and has an API. Outside of Europe, maybe ERA5 could be a last resort?

**Comment by jordanperr** [comment]
Is WRF data (WTK, New European Wind Atlas) considered to be "reanalysis" data? For the purposes of code organization, would you expect it to be present in PlantData.reanalysis? Or is this something else that should be handled by a one-off utility function.

**Comment by ejsimley** [comment]
@RHammond2 added you to this issue in case you'd like to look into factoring WTK out of QC into its own class.

**Comment by RHammond2** [comment]
Closed with #168
