### ISSUE TITLE
Is Contributing.md out of date? 

### ISSUE THREAD

**Issue by bburns632** [NREL/OpenOA#50]
Hello, 

I was reading the [contributing.md](https://github.com/NREL/OpenOA/blob/master/contributing.md), and it recommends branching off a release because the `develop` branch is not available on this public repo.  However, the `develop` branch is available, and its merge by @jordanperr was the last commit. 

So should I branch off `develop` for new PRs (and update the contributing.md) or would you prefer I branch off the `latest release` or off of `master`?

Thanks!

**Comment by jordanperr** [comment]
Yes, this is out of date. Please fork the repo and then branch off develop for new PRs, as you were expecting. I will update the contributing document to reflect this.

**Comment by bburns632** [comment]
Ok. Will do. Thanks for the clarification.
