### ISSUE TITLE
operational_AEP_analysis example

### ISSUE THREAD

**Issue by WindyMarkW** [NREL/OpenOA#56]
to get the last two examples to run, I had to change "sim_results" to "pa.results".

**Comment by jordanperr** [comment]
I have confirmed this was an oversight in the documentation. Will update in a future PR.

**Comment by jordanperr** [comment]
Hi @WindyMarkW, this issue has been resolved and merged in to the documentation in the Develop branch. I am closing the ticket. Thank you for this issue!
