### ISSUE TITLE
power curve splines is missing

### ISSUE THREAD

**Issue by sebasanper** [NREL/OpenOA#58]
in the Turbine_Toolkit_Examples.py file, there are references to power_curve.spline_fit, but that reference is missing in the power curve namespace.

**Comment by jordanperr** [comment]
Hi, Sebastian,

The documentation has been completely rewritten for the upcoming V2 release, and there is no longer a reference to "spline_fit" in the examples. This has been replaced with "gam" function in the power_curves module.

https://openoa.readthedocs.io/en/latest/examplesout.html#Power-curve-fitting

I will close this issue for now. Please re-open the issue if needed!
