### ISSUE TITLE
readthedocs is improperly configured

### ISSUE THREAD

**Issue by rafmudaf** [NREL/OpenOA#6]
There are a variety of errors generated when this project is linked to readtehdocs. Here are two examples: [mine](https://readthedocs.org/projects/raf-openoa/) and [openoa](https://readthedocs.org/projects/openoa/). Some of the errors are as simple as unmet requirements, while others are more subtle.

**Comment by jordanperr** [comment]
Up and running now. Thanks Rafael! This configuration requires entry of "sphinx/requirements.txt" in the ReadTheDocs settings.

https://openoa.readthedocs.io/en/latest/
