### ISSUE TITLE
Move large files to git lfs or other service

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#74]
There are now a couple large files in the repository which could be placed in an alternative system so old versions aren't tracked:

- Open\ OA\ Final\ Logos/ 6.8MB
-- Should all of these files even be included in this repository? I was imagining we'd have one small JPEG to be embedded in the readme and then host the source files somewhere else.
-- Zip the remaining files
- examples/data/la_haute_borne.zip: 35MB
-- I suggest we host this 35MB file on git-lfs
-- Should remove __MACOSX directory from zip file
- examples/turbine_level/data/example_20180829.zip 3.3MB
-- To delete
- examples/operational_AEP_analysis/data/eia_example_data.zip 9.4MB
-- To delete

**Comment by RHammond2** [comment]
This has been a low priority issue that the group has been continuously de-prioritized, so  I'm closing this out.
