### ISSUE TITLE
Documentation bugs

### ISSUE THREAD

**Issue by rafmudaf** [NREL/OpenOA#8]
I've come across a few places in the documentation where things are outdated or inconsistent, so I'd like to list them here for future reference.

- [x] The [contributing guidelines](https://github.com/NREL/OpenOA/blob/develop/contributing.md) mention a modified git flow with no `master` or `develop` branch but both are publicly accessible.
- [x] The [Documentation Style](https://github.com/NREL/OpenOA/blob/develop/contributing.md#documentation-style) section is unclear ... what will be discussed where?
- [x] Is there guidance on when or why to use the python3 version of the requirements file?
- [x] The [testing section](https://github.com/NREL/OpenOA/blob/develop/readme.md#testing) of the readme seems outdated. When I run `python setup.py test`, some tests fail due to the archive not yet being extracted. Further, when the archive is extracted another subfolder is created so the files have to be moved up a level.

Please let me know if I've overlooked some detail in providing feedback here.

Thanks for you work!

**Comment by sebastianpfaffel** [comment]
>     * The [testing section](https://github.com/NREL/OpenOA/blob/develop/readme.md#testing) of the readme seems outdated. When I run `python setup.py test`, some tests fail due to the archive not yet being extracted.

The turbine analysis example data set also extracts to a subfolder (".\OpenOA\examples\turbine_analysis\data\example_20180829\" instead of  ".\OpenOA\examples\turbine_analysis\data"). Thus, it fails to be loaded when following the examples. It has to be rezipped without the subfolder.

**Comment by jordanperr** [comment]
Good catches. I'll work on updating contributing.md.

The python3 version of requirements was needed last year, when some packages required different versions for python3 and python2. I believe the issue has been resolved with time, so I'll look into removing the python3 requirements now.

While possible, I don't like the idea of re-building the zip archive of test data. I'm unaware of a standard method used to download / extract testing data for this purpose. I see a couple solutions:

1. Update readme.md to reflect the extra step.
2. Add a script like "extract-data.sh" located in the root directory of the repository.
3. Add some python code to the unittest runners to ensure data is extracted.

I'm leaning towards solution 3.

**Comment by jordanperr** [comment]
All of these issues have been resolved in the V2 documentation. I am closing this issue!
