### ISSUE TITLE
Engie-API broken?

### ISSUE THREAD

**Issue by sltzgs** [NREL/OpenOA#87]
I tried to run the EngieTurbineData_Example notebook, but got the following error message:
![engie_import_error](https://user-images.githubusercontent.com/33449651/87307111-550d2300-c519-11ea-9f93-af4b687e6c91.png)
I think it might be a problem of the engie-opendata-platform, since manually entering the url (1) as well as testing their API directly (2) gives the same error:
(1) 
![image](https://user-images.githubusercontent.com/33449651/87309322-b97db180-c51c-11ea-8448-e08c2ccfeb8a.png)
(2)
![image](https://user-images.githubusercontent.com/33449651/87307925-b97cb200-c51a-11ea-96fa-9afa9b33dc0d.png)

Do you see the same problem or is it me? :) 
I have tried to contact them via the form on the homepage, will let you know if I get a response...

**Comment by moptis** [comment]
@sltzgs Yes we've found the same problem as well. We are just about ready to push an update that now hosts the Engie data on this repo. So very soon the API won't be an issue anymore.

**Comment by jordanperr** [comment]
@sltzgs, The new Engie Example which does not require API access is available on the Develop branch and will be included in the upcoming v2 tag. I will mark this issue as closed for now.

https://github.com/NREL/OpenOA/tree/develop
