### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bkramak** [NREL/OpenOA#98]
clean OS, anaconda downloaded and installed today.
point me in the right direction?

(base) bk@bk-Precision-M4700:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
(base) bk@bk-Precision-M4700:~$ conda activate openoa-env
(openoa-env) bk@bk-Precision-M4700:~$ pip install -r ./OpenOA/requirements.txt
Collecting numpy==1.14.0
  Using cached numpy-1.14.0.zip (4.9 MB)
Collecting scipy==1.0.0
  Using cached scipy-1.0.0.tar.gz (15.2 MB)
Collecting pandas==0.20.3
  Using cached pandas-0.20.3.tar.gz (10.4 MB)
Collecting geopandas==0.3.0
  Using cached geopandas-0.3.0-py2.py3-none-any.whl (888 kB)
Collecting pygam==0.4.0
  Using cached pygam-0.4.0-py2.py3-none-any.whl (775 kB)
Collecting tqdm==4.19.5
  Using cached tqdm-4.19.5-py2.py3-none-any.whl (51 kB)
Collecting statsmodels==0.8.0
  Using cached statsmodels-0.8.0.tar.gz (9.5 MB)
Collecting pytest==3.4.0
  Using cached pytest-3.4.0-py2.py3-none-any.whl (188 kB)
Collecting pytest-cov==2.5.1
  Using cached pytest_cov-2.5.1-py2.py3-none-any.whl (21 kB)
Collecting scikit_learn==0.18.1
  Using cached scikit-learn-0.18.1.tar.gz (8.9 MB)
Collecting matplotlib==2.1.0
  Using cached matplotlib-2.1.0.tar.gz (35.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/bk/anaconda3/envs/openoa-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5x6iqelu/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5x6iqelu/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sophqw7b
         cwd: /tmp/pip-install-5x6iqelu/matplotlib/
    Complete output (71 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.0]
                    python: yes [3.8.5 (default, Aug  5 2020, 08:36:46)  [GCC
                            7.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.0]
                       six: yes [using six version 1.15.0]
                  dateutil: yes [using dateutil version 2.8.1]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2020.1]
                    cycler: yes [cycler was not found. pip/easy_install may
                            attempt to install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: yes [version 1.6.37]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5x6iqelu/matplotlib/setup.py", line 216, in <module>
        pkg_help = pkg.install_help_msg()
      File "/tmp/pip-install-5x6iqelu/matplotlib/setupext.py", line 595, in install_help_msg
        release = platform.linux_distribution()[0].lower()
    AttributeError: module 'platform' has no attribute 'linux_distribution'
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.50]
                     latex: no
                   pdftops: yes [version 0.86.1]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(openoa-env) bk@bk-Precision-M4700:~$

**Comment by jordanperr** [comment]
Looks like its failing to install matplotlib v 2.1.0, and it's trying to install the source version of matplotlib.
We don't have any upper bound version on that package anymore, so it's odd that pip is choosing such an old version (2.1.0 was released in 2017).

1. Ensure you're using the latest version of OpenOA. The version string is visible in line 1 of [OpenOA/operational_analysis/__init__.py](https://github.com/NREL/OpenOA/blob/bc781d1defb3633b560071a57b14d7cc0fcc6274/operational_analysis/__init__.py#L1) Try `git checkout master; git pull` to make sure you're using the latest version.

2. If that doesn't work, you can try installing matplotlib manually:

`pip install matplotlib`

3. Or, to force a binary install of the latest version:

`pip install --only-binary :all: matplotlib==3.3.1`

4. Another approach would be to use anaconda to install the package:

`conda install matplotlib`

Please let me know if one of these approaches works for you.

**Comment by bkramak** [comment]
Thanks!bkBrian Kramak518-925-9030Sent using Zoho Mail ---- On Mon, 31 Aug 2020 21:19:42 -0400  notifications@github.com  wrote ----
Looks like its failing to install matplotlib v 2.1.0, and it's trying to install the source version of matplotlib.
We don't have any upper bound version on that package anymore, so it's odd that pip is choosing such an old version (2.1.0 was released in 2017).


Ensure you're using the latest version of OpenOA. The version string is visible in line 1 of OpenOA/operational_analysis/init.py Try git checkout master; git pull to make sure you're using the latest version.


If that doesn't work, you can try installing matplotlib manually:


pip install matplotlib

Or, to force a binary install of the latest version:

pip install --only-binary :all: matplotlib==3.3.1

Another approach would be to use anaconda to install the package:

conda install matplotlib
Please let me know if one of these approaches works for you.

**Comment by bkramak** [comment]
Manual install matplotlib got it to work. Thanks for the detailed response, very helpful. bkBrian Kramak518-925-9030Sent using Zoho Mail ---- On Mon, 31 Aug 2020 21:19:42 -0400  notifications@github.com  wrote ----
Looks like its failing to install matplotlib v 2.1.0, and it's trying to install the source version of matplotlib.
We don't have any upper bound version on that package anymore, so it's odd that pip is choosing such an old version (2.1.0 was released in 2017).


Ensure you're using the latest version of OpenOA. The version string is visible in line 1 of OpenOA/operational_analysis/init.py Try git checkout master; git pull to make sure you're using the latest version.


If that doesn't work, you can try installing matplotlib manually:


pip install matplotlib

Or, to force a binary install of the latest version:

pip install --only-binary :all: matplotlib==3.3.1

Another approach would be to use anaconda to install the package:

conda install matplotlib
Please let me know if one of these approaches works for you.
